services:
  web:
    build: .
    volumes:
      - log_files:/var/log/
    expose:
      - 5000
    env_file:
      - test.env
    command: python -m gunicorn app.run:app --workers=3 --bind 0.0.0.0:5000
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - log_files:/var/log/nginx
    ports:
      - "80:80"

  redis:
    image: redis:latest
    expose:
      - 6379

volumes:
  log_files: